FROM gradle:8.6-jdk21 AS builder
WORKDIR /app

COPY build.gradle* settings.gradle* ./
COPY gradle ./gradle

RUN gradle dependencies --no-daemon || true

COPY . .

# ENV SPRING_BOOT_MAIN_CLASS=com.example.YourApplication

RUN gradle bootJar --no-daemon

FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar", "--spring.profiles.active=prod"]
