spring:
  application:
    name: ListTick
  docker:
    compose:
      enabled: true
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/listtick 

datasource:
  database:
    account: jdbc:postgresql://localhost:5432/account
    bucket_list: jdbc:postgresql://localhost:5432/bucket_list
    note: jdbc:postgresql://localhost:5432/note
    notification: jdbc:postgresql://localhost:5432/notification
    shopping_list: jdbc:postgresql://localhost:5432/shopping_list
    task: jdbc:postgresql://localhost:5432/task
  user: postgres
  password: admin
  driver: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs

