spring:
  application:
    name: ListTick
  docker:
    compose:
      enabled: true
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/listtick

datasource:
  database:
    account_settings: jdbc:postgresql://localhost:5432/account_settings
    keycloak: jdbc:postgresql://localhost:5432/keycloak
    bucket_list: jdbc:postgresql://localhost:5432/bucket_list
    note: jdbc:postgresql://localhost:5432/note
    notification: jdbc:postgresql://localhost:5432/notification
    shopping_list: jdbc:postgresql://localhost:5432/shopping_list
    task: jdbc:postgresql://localhost:5432/task
  user: postgres
  password: admin
  driver: org.postgresql.Driver
  dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
    oauth:
      client-id: listtick-swagger
      use-pkce-with-authorization-code-grant: true
      scopes:
        - openid
        - profile
        - email

keycloak:
  auth:
    server:
      url: http://localhost:8090
  realm: listtick
  event:
    secret: "KEjG2q8P4nX9vM3tL5wY7bR1cV6hN0dS"